### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by duaneya** [Technologicat/python-wlsqm#2]
brilliant work！but I have some problems
python3.6
pip install wlsqm

```bash
wlsqm/utils/lapackdrivers.pyx:1740:38: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                         ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:42: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                            ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:45: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                        ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:57: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                              ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:63: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                                          ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:75: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                                                 ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:82: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                                                         ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:90: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, &worksize, &lwork, &info )
    lwork  = <int>worksize
    cdef double* p_work = <double*>malloc( lwork*sizeof(double) )

    # LDA(A) = n
    dgesvd( &jobu, &jobvt, &m, &n, A, &m, S, <double*>0, &ldu, <double*>0, &ldvt, p_work, &lwork, &info )
                                                                                                 ^
------------------------------------------------------------

wlsqm/utils/lapackdrivers.pyx:1740:98: Converting to Python object not allowed without gil
Traceback (most recent call last):
  File "setup.py", line 220, in <module>
    gdb_debug = debug ),
  File "/home/duan/miniconda3/envs/cv/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/home/duan/miniconda3/envs/cv/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: wlsqm/utils/lapackdrivers.pyx
```
use python3.4
successful installed, but 
```python
>>> import wlsqm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/duan/PycharmProjects/vessel/python-wlsqm/wlsqm/__init__.py", line 26, in <module>
    from .fitter.defs   import *  # definitions (constants) (common)
ImportError: No module named 'wlsqm.fitter.defs'
>>> 
```

**Comment by Technologicat** [comment]
Hmm, probably something relevant has changed between Python 3.4 and 3.6. Since the official support for Python 3.4 just ended this March, I'll be upgrading soon, and then I can take a look at it. Thanks for the heads-up!

Not working in 3.4 is definitely a bug, but it seems I can't reproduce it. I tried a clean reinstall of ``wlsqm`` on my machine with (Linux, Python 3.4) and ``import wlsqm`` completes without error. So let's debug. How did you install the package? From ``pip`` or by ``python3 setup.py install --user``?

**Comment by Technologicat** [comment]
Ah, right, you already said at the top that it was a pip install :)

I'll check my packaging logic and comment here when done...

**Comment by Technologicat** [comment]
Ok, checked. ``setup.py`` seems to be ok. It's compiling the ``wlsqm.fitter.defs`` module, as well as including it into the distribution (checked by a clean ``pip3 install wlsqm`` and then manually verifying the exact ``.tar.gz`` file it said it downloaded). For me ``wlsqm`` still works after the clean install via pip.

One possibility is, did your terminal happen to be in the ``python-wlsqm`` directory when you started ``python3`` and invoked ``import wlsqm``? In that case Python will find the local ``wlsqm`` subdirectory instead of the installed ``wlsqm`` package.

(Loading from the local directory doesn't work, because the compiled Cython modules won't exist there.)

**Comment by duaneya** [comment]
> Ok, checked. `setup.py` seems to be ok. It's compiling the `wlsqm.fitter.defs` module, as well as including it into the distribution (checked by a clean `pip3 install wlsqm` and then manually verifying the exact `.tar.gz` file it said it downloaded). For me `wlsqm` still works after the clean install via pip.
> 
> One possibility is, did your terminal happen to be in the `python-wlsqm` directory when you started `python3` and invoked `import wlsqm`? In that case Python will find the local `wlsqm` subdirectory instead of the installed `wlsqm` package.
> 
> (Loading from the local directory doesn't work, because the compiled Cython modules won't exist there.)

**Comment by duaneya** [comment]
thanks，the proplem is `in the python-wlsqm directory`
